name: Spring Boot CI

on:
  push:
    branches:
      - development
      - 'releases/**'
      
  pull_request:
    branches:
      - development
      - 'releases/**'
      

jobs:
  build-with-gradle:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          
      - name: gradlew에 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Cache Gradle packages 
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          
      - name: Build with Gradle
        run: ./gradlew build
